// This file defines what instructions are unsupported

UNSUPPORTED_ATTRIBUTE(XED_ATTRIBUTE_RING0);
UNSUPPORTED_ATTRIBUTE(XED_ATTRIBUTE_PROTECTED_MODE);

UNSUPPORTED_ISA_SET(XED_ISA_SET_VTX);
UNSUPPORTED_ISA_SET(XED_ISA_SET_RTM);
UNSUPPORTED_ISA_SET(XED_ISA_SET_TDX);
UNSUPPORTED_ISA_SET(XED_ISA_SET_UINTR);

UNSUPPORTED_ISA_SET_RANGE(XED_ISA_SET_APX_F, XED_ISA_SET_APX_F_VMX);

UNSUPPORTED_ICLASS(XED_ICLASS_CLI);
UNSUPPORTED_ICLASS(XED_ICLASS_STI);
UNSUPPORTED_ICLASS(XED_ICLASS_MCOMMIT);
UNSUPPORTED_ICLASS(XED_ICLASS_RDRAND);
UNSUPPORTED_ICLASS(XED_ICLASS_RDSEED);

UNSUPPORTED_CATEGORY(XED_CATEGORY_PTWRITE);
